package com.ejemplo.model;

// Generated 10-jul-2013 11:53:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.*;
/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "tarjeta")
@NamedQuery(name = "Tarjeta.findAll", query = "SELECT t FROM Tarjeta t")
public class Tarjeta implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	@Id
	@SequenceGenerator(name = "tarjetasequence", sequenceName = "tarjetasequence", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tarjetasequence")
	private long id;
	private long nrotarjeta;
	private String ciudad;
	private Integer digitoverificador;
	private String direccion;
	@Temporal(TemporalType.DATE)
	private Date fechadevencimiento;
	private String marca;
	private String nombre;
	private String observaciones;
	private String telefono;
	
	

	public Tarjeta() {
	}
/*
	public Tarjeta(long id, long nrotarjeta) {
		this.id = id;
		this.nrotarjeta = nrotarjeta;
	}

	public Tarjeta(long id, long nrotarjeta, String ciudad,
			Integer digitoverificador, String direccion,
			Date fechadevencimiento, String marca, String nombre,
			String observaciones, String telefono, Set<OrdenCompra> ordenCompras) {
		this.id = id;
		this.nrotarjeta = nrotarjeta;
		this.ciudad = ciudad;
		this.digitoverificador = digitoverificador;
		this.direccion = direccion;
		this.fechadevencimiento = fechadevencimiento;
		this.marca = marca;
		this.nombre = nombre;
		this.observaciones = observaciones;
		this.telefono = telefono;
		this.ordenCompras = ordenCompras;
	}
	*/

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nrotarjeta", nullable = false)
	public long getNrotarjeta() {
		return this.nrotarjeta;
	}

	public void setNrotarjeta(long nrotarjeta) {
		this.nrotarjeta = nrotarjeta;
	}

	@Column(name = "ciudad")
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "digitoverificador")
	public Integer getDigitoVerificador() {
		return this.digitoverificador;
	}

	public void setDigitoVerificador(Integer digitoverificador) {
		this.digitoverificador = digitoverificador;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechadevencimiento", length = 13)
	public Date getFechaDeVencimiento() {
		return this.fechadevencimiento;
	}

	public void setFechaDeVencimiento(Date fechadevencimiento) {
		this.fechadevencimiento = fechadevencimiento;
	}

	@Column(name = "marca")
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
/*
 
 
	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<OrdenCompra> getOrdencompras() {
		return this.ordenCompras;
	}

	public void setOrdencompras(Set<OrdenCompra> ordenCompras) {
		this.ordenCompras = ordenCompras;
	}
*/
}
